version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/lessgo ./cmd/lessgo

  test:
    desc: Run all tests with race detection and 10 iterations (CSS rendering must be fast)
    cmds:
      # CSS rendering should complete quickly - strict 5s timeout enforces performance
      - go test -timeout 5s -race -failfast -count=10 ./...
      - go test -timeout 5s -race -failfast -count=10 ./testdata -v

  test:fixture:
    desc: Run fixture tests only with 10 iterations
    cmds:
      - go test -timeout 5s -race -failfast -count=10 ./testdata -v

  test:lexer:
    desc: Run lexer tests only
    cmds:
      - go test -timeout 5s ./parser -v

  fmt:
    desc: Format all Go files
    cmds:
      - goimports -w .
      - go fmt ./...

  fmt:less:
    desc: Format LESS files using lessgo fmt command
    cmds:
      - task: build
      - ./bin/lessgo fmt "{{.CLI_ARGS}}"

  watch:
    desc: Watch for changes and run tests
    cmds:
      - task: fmt
      - task: test

  default:
    cmds:
      - task: fmt
      - task: test
