version: '3'

includes:
  mdox: ./Taskfile.mdox.yml

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/lessgo ./cmd/lessgo

  test:
    desc: "Run tests and collect coverage"
    deps:
      - fmt
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
    cmds:
      - go test -timeout 5s -failfast -count=1 -cover -coverpkg=./... -coverprofile=pkg.cov ./...

  cover:
    desc: "Show source coverage"
    cmds:
      - go-fsck extract . --include-sources
      - go-fsck docs > docs/api.md
      - go tool cover -func=pkg.cov | summary coverfunc --json > pkg.cov.json
      - go-fsck extract --pretty-json ./...
      - go-fsck coverage -c pkg.cov.json -o go-fsck.json
      - go-fsck coverage --template=docs/testing-coverage.md.tpl -v > docs/testing-coverage.md
      - perl -pi -e 's/github.com\/titpetric/titpetric/g' docs/testing-coverage.md
      - task: mdox:fmt

  test:fixture:
    desc: Run fixture tests only with 10 iterations
    cmds:
      - go test -timeout 5s -race -failfast -count=10 ./testdata -v

  test:lexer:
    desc: Run lexer tests only
    cmds:
      - go test -timeout 5s ./parser -v

  fmt:
    desc: Format all Go files
    cmds:
      - goimports -w .
      - go fmt ./...

  fmt:less:
    desc: Format LESS files using lessgo fmt command
    cmds:
      - task: build
      - ./bin/lessgo fmt "{{.CLI_ARGS}}"

  watch:
    desc: Watch for changes and run tests
    cmds:
      - task: fmt
      - task: test

  default:
    cmds:
      - task: fmt
      - task: test
